import { USER_MESSAGES } from "./types";

export type Locale = "en" | "si" | "ta";

export const LOCALES: readonly Locale[] = ["en", "si", "ta"] as const;

export const LOCALE_LABELS: Record<Locale, string> = {
  en: "EN",
  si: "සිං",
  ta: "த",
};

const extraEn = {
  skipToContent: "Skip to content",
  join: "Join",
  continueWithGoogle: "Continue with Google",
  joinTesterGroup: "Join the tester group",
  joinPlayAndInstall: "Join Play test and install",
  stepJoinGroup: "Join group",
  stepCheckAccess: "Check access",
  stepInstallApp: "Install app",
  step1Title: "1. Join the tester group",
  step2Title: "2. Check access",
  step3Title: "3. Join Play test, then install",
  openTesterGroup: "Open Tester Group",
  openTesterGroupAgain: "Open Tester Group again",
  openTesterGroupAria: "Open Tester Group (opens in a new tab)",
  checkMyAccess: "Check My Access",
  checking: "Checking…",
  joinGooglePlayTest: "Join Google Play Test",
  joinPlayAria: "Join Google Play Test (opens in a new tab)",
  installApp: "Install AAC-Sinhala",
  installAria: "Install AAC-Sinhala (opens in a new tab)",
  loading: "Loading…",
  loadingGoogle: "Loading Google…",
  tapJoinGroup: "Tap Join group",
  closeJoinInstructions: "Close join instructions",
  theApp: "The app",
  fieldVisit: "Field visit",
  fieldPragathi: "Pragathi",
  noPassword: "This site never asks for a password.",
  feedback: "Feedback",
  feedbackType: "Feedback type",
  messageLabel: "Message",
  screenshotOptional: "Screenshot (optional)",
  sendFeedbackBtn: "Send feedback",
  sending: "Sending…",
  invalidEmailUi: "Please enter a valid email address.",
  messageTooShort: "Please include a short description (at least 10 characters).",
  tryAgain: "Please try again in a moment.",
  language: "Language",
  accountWarning: "Google account warning",
  onboardingSteps: "Onboarding steps",
  feedbackTypeBug: "Bug",
  feedbackTypeSuggestion: "Suggestion",
  feedbackTypeUsability: "Usability",
  feedbackTypeAccessibility: "Accessibility",
  feedbackTypeOther: "Other",
  registerWithEmail: "Register with email",
  orRegisterEmail: "Or register with your Play Store email",
  emailRegistered: "Registered with this email",
  getOnGooglePlay: "Get it on Google Play",
  caseStudy: "Case study",
  gallery: "Gallery",
  downloadTheQr: "Download the QR",
  qrLead: "Scan to open the AAC Sinhala tester portal.",
  printQrPasses: "Print A4 QR passes",
  printQrPassesLead: "One A4 sheet, two laminated passes. Cut down the middle.",
  contact: "Contact",
  contactName: "Yasas Pasindu Fernando",
  contactLocation: "Hikkaduwa, Sri Lanka",
    fieldExposure: "Field exposure",
  chatTitle: "Ask AAC",
  chatLead: "A helper for joining, Play Store, feedback, and the Smart AAC case study.",
  chatWelcome:
    "Hi — I can help you join the tester group, install from Play, send feedback, or open the case study. Google Sign-In is not the same as being in the group.",
  chatPlaceholder: "Ask about joining, Play Store, or the app…",
  chatSend: "Send",
  chatClose: "Close chat",
  chatTapToAsk: "Tap to ask",
  chatDismissTip: "Dismiss tip",
  siteTitle: "AAC Sinhala — Closed testing",
  siteDescription: "Join the AAC Sinhala closed beta. Communication support for children who need a voice.",
  continueWithGoogleAria: "Continue with Google",
  qrAlt: "QR code for https://aac.yasaboy.com/",
  guideJoinAlt: "Google Groups page with a yellow arrow pointing to the Join group button",
  fieldCentre: "Centre",
  fieldContext: "Context",
  appScreensAria: "AAC Sinhala app screens in iPhone frames",
  appHomeTitle: "Home",
  appHomeBody: "Choose a category, build a message, and speak it aloud.",
  appHomeAlt: "AAC Sinhala home screen with message composer and categories",
  appCardsTitle: "Picture cards",
  appCardsBody: "Large, easy-to-tap cards for books, food, play, and more.",
  appCardsAlt: "AAC Sinhala picture cards for everyday words",
  appEmotionTitle: "Emotion camera",
  appEmotionBody: "A calm camera view for supportive expression cues.",
  appEmotionAlt: "AAC Sinhala emotion camera screen",
  appSettingsTitle: "Settings",
  appSettingsBody: "Language and category choices for home and school.",
  appSettingsAlt: "AAC Sinhala settings and category preferences",
  closeScreenshot: "Close screenshot",
  enlargeScreenshot: "Enlarge screenshot",
  tapToEnlarge: "Tap the picture to enlarge",
  adminTitle: "Tester admin",
  adminLead:
    "Protected by Cloudflare Access. Emails stay on this page. Google Sign-In and typed email both create tester rows. Link clicks are recorded events, not Google membership or Play download proof.",
  adminExportCsv: "Export CSV",
  adminProtected: "Admin access is protected by Cloudflare Access.",
  adminTotalRequests: "Total tester requests",
  adminGoogleSignups: "Google signups",
  adminEmailSignups: "Email signups",
  adminFeedbackCount: "Feedback count",
  adminPendingGroup: "Pending group joins",
  adminPendingPlay: "Pending Play joins",
  adminCompletedFlows: "Completed onboarding flows",
  adminNeedsAttention: "Needs attention",
  adminVerifiedMemberships: "Verified Google Group memberships:",
  adminVerifiedHint: "If this is 0, membership verification is unavailable for the consumer group.",
  adminRegistrants: "Registrants",
  adminTesterRequests: "Tester requests",
  adminColEmail: "Email",
  adminColSignup: "Signup",
  adminColStatus: "Status",
  adminColRequested: "Requested",
  adminColLastActivity: "Last activity",
  adminColGroup: "Group",
  adminColMembership: "Membership",
  adminOpened: "Opened",
  adminVerified: "Verified",
  adminNotVerified: "Not verified",
  adminSignupGoogle: "Google",
  adminSignupEmail: "Email",
  adminNoFeedback: "No feedback yet.",
  adminScreenshotAttached: "Screenshot attached",
} as const;

export const UI_COPY = {
  en: {
    ...USER_MESSAGES,
    ...extraEn,
  },
  si: {
    ...USER_MESSAGES,
    ...extraEn,
    skipToContent: "අන්තර්ගතයට යන්න",
    join: "එක්වන්න",
    continueWithGoogle: "Google සමඟ ඉදිරියට යන්න",
    joinTesterGroup: "පරීක්ෂක කණ්ඩායමට එක්වන්න",
    joinPlayAndInstall: "Play පරීක්ෂණයට එක්වී ස්ථාපනය කරන්න",
    stepJoinGroup: "කණ්ඩායමට එක්වන්න",
    stepCheckAccess: "ප්‍රවේශය බලන්න",
    stepInstallApp: "යෙදුම ස්ථාපනය",
    step1Title: "1. පරීක්ෂක කණ්ඩායමට එක්වන්න",
    step2Title: "2. ප්‍රවේශය බලන්න",
    step3Title: "3. Play පරීක්ෂණයට එක්වී ස්ථාපනය කරන්න",
    openTesterGroup: "පරීක්ෂක කණ්ඩායම විවෘත කරන්න",
    openTesterGroupAgain: "පරීක්ෂක කණ්ඩායම නැවත විවෘත කරන්න",
    openTesterGroupAria: "පරීක්ෂක කණ්ඩායම විවෘත කරන්න (නව ටැබයක)",
    checkMyAccess: "මගේ ප්‍රවේශය පරීක්ෂා කරන්න",
    checking: "පරීක්ෂා කරමින්…",
    joinGooglePlayTest: "Google Play පරීක්ෂණයට එක්වන්න",
    joinPlayAria: "Google Play පරීක්ෂණයට එක්වන්න (නව ටැබයක)",
    installApp: "AAC-Sinhala ස්ථාපනය කරන්න",
    installAria: "AAC-Sinhala ස්ථාපනය කරන්න (නව ටැබයක)",
    loading: "පූරණය වෙමින්…",
    loadingGoogle: "Google පූරණය වෙමින්…",
    tapJoinGroup: "Join group ඔබන්න",
    closeJoinInstructions: "උපදෙස් වසන්න",
    theApp: "යෙදුම",
    fieldVisit: "ක්ෂේත්‍ර සංචාරය",
    fieldPragathi: "ප්‍රගති",
    noPassword: "මෙම අඩවිය කිසිදා මුරපදයක් ඉල්ලන්නේ නැත.",
    feedback: "ප්‍රතිපෝෂණය",
    feedbackType: "ප්‍රතිපෝෂණ වර්ගය",
    messageLabel: "පණිවිඩය",
    screenshotOptional: "තිර රුව (අත්‍යවශ්‍ය නැත)",
    sendFeedbackBtn: "ප්‍රතිපෝෂණය යවන්න",
    sending: "යවමින්…",
    invalidEmailUi: "වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.",
    messageTooShort: "අඩුම තරමේ අකුරු 10ක කෙටි විස්තරයක් ඇතුළත් කරන්න.",
    tryAgain: "මඳ වේලාවකින් නැවත උත්සාහ කරන්න.",
    language: "භාෂාව",
    accountWarning: "Google ගිණුම් අනතුරු ඇඟවීම",
    onboardingSteps: "එක්වීමේ පියවර",
    feedbackTypeBug: "දෝෂයක්",
    feedbackTypeSuggestion: "යෝජනාවක්",
    feedbackTypeUsability: "භාවිතය",
    feedbackTypeAccessibility: "ප්‍රවේශ්‍යතාව",
    feedbackTypeOther: "වෙනත්",
    joinBetaTitle: "AAC සිංහල බීටාවට එක්වන්න",
    joinBetaSubtitle: "ඔබේ Android දුරකථනයේ භාවිතා කරන Google ගිණුම භාවිතා කරන්න.",
    googleVerified: "Google ගිණුම තහවුරු විය",
    googleSignInFailed: "Google පිවිසුම සම්පූර්ණ නොවීය. නැවත උත්සාහ කරන්න.",
    googleSignInUnavailable: "Google පිවිසුම තවම සකසා නැත.",
    useDifferentAccount: "වෙනත් Google ගිණුමක් භාවිතා කරන්න",
    signOut: "ඉවත් වන්න",
    playStoreEmailLabel: "ඔබේ Google Play ගිණුම",
    playAccountImportant: "එකම Google ගිණුම භාවිතා කරන්න",
    sameAccountGroupsAndPlay: "පරීක්ෂක කණ්ඩායමට සහ Google Play සඳහා එකම Google ගිණුම භාවිතා කරන්න.",
    useThisSameAccountForGroup: "පරීක්ෂක කණ්ඩායමට එක්වන විට මෙම Google ගිණුමම භාවිතා කරන්න.",
    switchIfAnotherAccount:
      "Google Groups හි වෙනත් ගිණුමක් සක්‍රිය නම්, Join group ඔබන්නට පෙර ඉහත පෙන්වන ගිණුමට මාරු වන්න.",
    afterJoinCheck: "එක්වීමෙන් පසු මෙහි ආපසු එන්න, Check My Access ඔබන්න.",
    groupsNewTabHint: "Google Groups නව ටැබයක විවෘත වේ. මෙම පිටුව විවෘතව තිබේ.",
    lookForJoinGroup: "Join group බොත්තම සොයන්න",
    inTheGroup: "ඔබ පරීක්ෂක කණ්ඩායමේ සිටී",
    playUsingSame: "Google Play එකම ගිණුම භාවිතා කරනවාදැයි බලන්න.",
    feedbackPrompt: "දෝෂයක් හෝ යෝජනාවක් තිබේද?",
    sendFeedback: "ප්‍රතිපෝෂණය යවන්න",
    wrongAccountHeading: "වැරදි Google ගිණුමක්ද?",
    wrongAccountHelp:
      "Google Groups වෙත ආපසු ගොස්, ඉහත පෙන්වන Google ගිණුමට මාරු වී, පරීක්ෂක කණ්ඩායමට නැවත එක්වන්න.",
    checkAccessNotMember: "මෙම Google ගිණුම පරීක්ෂක කණ්ඩායමේ තවම හමු නොවීය.",
    checkAccessUnavailable: "සාමාජිකත්වය තහවුරු කිරීම දැන් ලබාගත නොහැක.",
    feedbackThanks: "ස්තුතියි. ඔබේ ප්‍රතිපෝෂණය පෞද්ගලිකව සුරකින ලදී.",
    searchGroupHint:
      "Google Groups මෙම ගිණුමෙන් පිවිසී නැත්නම්, අපේ පරීක්ෂක කණ්ඩායම සොයා එක්වන්න.",
    copyGroupName: "කණ්ඩායම් නම පිටපත් කරන්න",
    groupNameCopied: "පිටපත් විය",
    registerWithEmail: "ඊමේල් එකෙන් ලියාපදිංචි වන්න",
    orRegisterEmail: "නැතහොත් ඔබේ Play Store ඊමේල් එකෙන් ලියාපදිංචි වන්න",
    emailRegistered: "මෙම ඊමේල් ලිපිනයෙන් ලියාපදිංචි විය",
    getOnGooglePlay: "Google Play වෙතින් ලබා ගන්න",
    caseStudy: "අධ්‍යයනය",
    gallery: "ගැලරිය",
    downloadTheQr: "QR බාගන්න",
    qrLead: "AAC සිංහල පරීක්ෂක ද්වාරය විවෘත කිරීමට ස්කෑන් කරන්න.",
    printQrPasses: "A4 QR pass මුද්‍රණය",
    printQrPassesLead: "A4 පිටුවක්, laminated pass දෙකක්. මැදින් කපන්න.",
    contact: "සම්බන්ධ වන්න",
    contactName: "Yasas Pasindu Fernando",
    contactLocation: "හික්කඩුව, ශ්‍රී ලංකාව",
    fieldExposure: "ක්ෂේත්‍ර නිරාවරණය",
    chatTitle: "AAC අසන්න",
    chatLead: "එක්වීම, Play Store, ප්‍රතිපෝෂණය සහ Smart AAC අධ්‍යයනය සඳහා උපකාරකයකි.",
    chatWelcome:
      "ආයුබෝවන් — පරීක්ෂක කණ්ඩායම, Play ස්ථාපනය, ප්‍රතිපෝෂණය හෝ අධ්‍යයනය ගැන උදව් කළ හැකිය. Google පිවිසුම කණ්ඩායමේ සාමාජිකත්වය නොවේ.",
    chatPlaceholder: "එක්වීම, Play Store, යෙදුම ගැන අසන්න…",
    chatSend: "යවන්න",
    chatClose: "චැට් වසන්න",
    chatTapToAsk: "අහන්න තට්ටු කරන්න",
    chatDismissTip: "ඉඟිය වසන්න",
    invalidEmail: "කරුණාකර වලංගු Google ගිණුම් ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.",
    rateLimited: "ඉල්ලීම් වැඩියි. මිනිත්තු කිහිපයක් රැඳී නැවත උත්සාහ කරන්න.",
    almostReady: "ඔබ ආසන්නයේ සූදානම්!",
    sameAccount: "ඔබ ලියාපදිංචි වූ එකම Google ගිණුම භාවිතා කරන්න.",
    deviceAccount: "ඔබේ Android උපාංගයේ එකම Play Store ගිණුම භාවිතා කරන්න.",
    playStoreEveryone: "සැමටම Google Play හි භාවිතා කරන Google ගිණුම භාවිතා කළ යුතුය.",
    playStoreEmailHint: "මෙය ඔබේ Android උපාංගයේ භාවිතා වන Google ගිණුමයි.",
    googleMissingEmail: "Google මෙම ගිණුම සඳහා ඊමේල් ලිපිනයක් බෙදා ගත්තේ නැත.",
    signInRequired: "ඉදිරියට යාමට Google සමඟ ඉදිරියට යන්න.",
    joinGroupHint: "කණ්ඩායම විවෘත කර Join group ඔබන්න. ඔබේ Play Store ගිණුම භාවිතා කරන්න.",
    joinGroupModalTitle: "AAC සිංහල පරීක්ෂකයන්ට එක්වන්න",
    joinGroupModalLead: "AAC සිංහල බීටාවට එක්වීමට තව පියවරක් ඉතිරියි.",
    playAccountShort: "Google Play හි භාවිතා කරන එකම Google ගිණුම භාවිතා කරන්න.",
    usePlayStoreAccount: "කණ්ඩායමට එක්වීමට ඔබේ Play Store ගිණුම භාවිතා කරන්න.",
    usePlayStoreAccountHeading: "ඔබේ Play Store ගිණුම භාවිතා කරන්න",
    sameAccountPlayAndGroup: "පරීක්ෂක කණ්ඩායමට සහ Google Play පරීක්ෂණයට මෙම ගිණුමම භාවිතා කරන්න.",
    accountEnteredLabel: "ඔබේ Google Play ගිණුම",
    authenticatedAccountIs: "ඔබ සත්‍යාපනය කළ ගිණුම:",
    whenJoiningExactAccount:
      "පරීක්ෂක කණ්ඩායමට එක්වන විට, Google Groups මෙම ගිණුමෙන්ම පිවිසී ඇති බව තහවුරු කරන්න.",
    groupsSignedInWarning: "Google Groups මෙම ගිණුමෙන්ම පිවිසී ඇති බව තහවුරු කරන්න.",
    beforeJoiningSignedIn: "එක්වීමට පෙර, Google Groups පිවිසී ඇත්තේ:",
    alreadyJoined: "දැනටමත් එක්වී තිබේද?",
    nextPlayTest: "Google Play පරීක්ෂණයට එක්වන්න",
    joinPlayTestHint: "දැන් එකම Google ගිණුමෙන් Google Play පරීක්ෂණ පිටුව විවෘත කරන්න.",
    installTitle: "AAC-Sinhala ස්ථාපනය කරන්න",
    installHint: "පරීක්ෂණයට එක්වූ පසු, ඔබේ Android දුරකථනයේ Google Play වෙතින් AAC-Sinhala ස්ථාපනය කරන්න.",
    startTestingTitle: "පරීක්ෂණය අරඹන්න",
    startTestingHint: "AAC-Sinhala විවෘත කර සන්නිවේදන විශේෂාංග උත්සාහ කරන්න.",
    checkAccessNotDetected: "මෙම Google ගිණුම පරීක්ෂක කණ්ඩායමේ තවම හමු නොවීය.",
    checkAccessRetry: "ඉහත පෙන්වන Google ගිණුමෙන් කණ්ඩායමට එක්වූ බව තහවුරු කර, නැවත උත්සාහ කරන්න.",
    verificationUnavailable: "සාමාජිකත්ව තහවුරු කිරීම ලබාගත නොහැක",
    ready: "ඔබ සූදානම්!",
    readyToTest: "ඔබ AAC සිංහල පරීක්ෂණයට සූදානම්",
    siteTitle: "AAC සිංහල — වසා පරීක්ෂණය",
    siteDescription: "AAC සිංහල වසා බීටාවට එක්වන්න. කටහඬක් අවශ්‍ය දරුවන්ට සන්නිවේදන සහාය.",
    continueWithGoogleAria: "Google සමඟ ඉදිරියට යන්න",
    qrAlt: "https://aac.yasaboy.com/ සඳහා QR කේතය",
    guideJoinAlt: "Join group බොත්තමට කහ ඊතලයක් යොමු කරන Google Groups පිටුව",
    fieldCentre: "මධ්‍යස්ථානය",
    fieldContext: "සන්දර්භය",
    appScreensAria: "iPhone රාමු තුළ AAC සිංහල යෙදුම් තිර",
    appHomeTitle: "මුල් පිටුව",
    appHomeBody: "ප්‍රවර්ගයක් තෝරා, පණිවිඩයක් සාදා, එය ශබ්දයෙන් කියවන්න.",
    appHomeAlt: "පණිවිඩ සම්පාදකය සහ ප්‍රවර්ග සහිත AAC සිංහල මුල් තිරය",
    appCardsTitle: "පින්තූර කාඩ්පත්",
    appCardsBody: "පොත්, ආහාර, සෙල්ලම් සහ තවත් දේ සඳහා ලොකු, පහසුවෙන් තට්ටු කළ හැකි කාඩ්පත්.",
    appCardsAlt: "එදිනෙදා වචන සඳහා AAC සිංහල පින්තූර කාඩ්පත්",
    appEmotionTitle: "හැඟීම් කැමරාව",
    appEmotionBody: "සහායක ඉංගිත ඉඟි සඳහා සන්සුන් කැමරා දසුනක්.",
    appEmotionAlt: "AAC සිංහල හැඟීම් කැමරා තිරය",
    appSettingsTitle: "සැකසුම්",
    appSettingsBody: "නිවස සහ පාසල සඳහා භාෂා සහ ප්‍රවර්ග තේරීම්.",
    appSettingsAlt: "AAC සිංහල සැකසුම් සහ ප්‍රවර්ග මනාප",
    closeScreenshot: "තිර රුව වසන්න",
    enlargeScreenshot: "තිර රුව විශාල කරන්න",
    tapToEnlarge: "විශාල කිරීමට පින්තූරය තට්ටු කරන්න",
    adminTitle: "පරීක්ෂක පරිපාලනය",
    adminLead:
      "Cloudflare Access මගින් ආරක්ෂිතයි. ඊමේල් මෙම පිටුවේම තියෙනවා. Google පිවිසුම සහ ටයිප් කළ ඊමේල් දෙකම පරීක්ෂක පේළි සාදයි. සබැඳි ක්ලික් සිදුවීම් පමණි, Google සාමාජිකත්වය හෝ Play බාගැනීම් සාක්ෂිය නොවේ.",
    adminExportCsv: "CSV බාගන්න",
    adminProtected: "පරිපාලක ප්‍රවේශය Cloudflare Access මගින් ආරක්ෂිතයි.",
    adminTotalRequests: "මුළු පරීක්ෂක ඉල්ලීම්",
    adminGoogleSignups: "Google ලියාපදිංචි",
    adminEmailSignups: "ඊමේල් ලියාපදිංචි",
    adminFeedbackCount: "ප්‍රතිපෝෂණ ගණන",
    adminPendingGroup: "බලාපොරොත්තු කණ්ඩායම් එක්වීම්",
    adminPendingPlay: "බලාපොරොත්තු Play එක්වීම්",
    adminCompletedFlows: "අවසන් වූ එක්වීමේ ප්‍රවාහ",
    adminNeedsAttention: "අවධානය අවශ්‍යයි",
    adminVerifiedMemberships: "තහවුරු වූ Google Group සාමාජිකත්ව:",
    adminVerifiedHint: "මෙය 0 නම්, පාරිභෝගික කණ්ඩායමට සාමාජිකත්ව තහවුරු කිරීම ලබාගත නොහැක.",
    adminRegistrants: "ලියාපදිංචි වූවන්",
    adminTesterRequests: "පරීක්ෂක ඉල්ලීම්",
    adminColEmail: "ඊමේල්",
    adminColSignup: "ලියාපදිංචිය",
    adminColStatus: "තත්ත්වය",
    adminColRequested: "ඉල්ලුවේ",
    adminColLastActivity: "අවසන් ක්‍රියාකාරකම",
    adminColGroup: "කණ්ඩායම",
    adminColMembership: "සාමාජිකත්වය",
    adminOpened: "විවෘත කළා",
    adminVerified: "තහවුරුයි",
    adminNotVerified: "තහවුරු නැත",
    adminSignupGoogle: "Google",
    adminSignupEmail: "ඊමේල්",
    adminNoFeedback: "තවම ප්‍රතිපෝෂණයක් නැත.",
    adminScreenshotAttached: "තිර රුව අමුණා ඇත",
  },
  ta: {
    ...USER_MESSAGES,
    ...extraEn,
    skipToContent: "உள்ளடக்கத்திற்குச் செல்லவும்",
    join: "சேரவும்",
    continueWithGoogle: "Google மூலம் தொடரவும்",
    joinTesterGroup: "சோதனையாளர் குழுவில் சேரவும்",
    joinPlayAndInstall: "Play சோதனையில் சேர்ந்து நிறுவவும்",
    stepJoinGroup: "குழுவில் சேரவும்",
    stepCheckAccess: "அணுகலைச் சரிபார்க்கவும்",
    stepInstallApp: "செயலியை நிறுவவும்",
    step1Title: "1. சோதனையாளர் குழுவில் சேரவும்",
    step2Title: "2. அணுகலைச் சரிபார்க்கவும்",
    step3Title: "3. Play சோதனையில் சேர்ந்து நிறுவவும்",
    openTesterGroup: "சோதனையாளர் குழுவைத் திறக்கவும்",
    openTesterGroupAgain: "சோதனையாளர் குழுவை மீண்டும் திறக்கவும்",
    openTesterGroupAria: "சோதனையாளர் குழுவைத் திறக்கவும் (புதிய தாவல்)",
    checkMyAccess: "என் அணுகலைச் சரிபார்க்கவும்",
    checking: "சரிபார்க்கிறது…",
    joinGooglePlayTest: "Google Play சோதனையில் சேரவும்",
    joinPlayAria: "Google Play சோதனையில் சேரவும் (புதிய தாவல்)",
    installApp: "AAC-Sinhala-ஐ நிறுவவும்",
    installAria: "AAC-Sinhala-ஐ நிறுவவும் (புதிய தாவல்)",
    loading: "ஏற்றுகிறது…",
    loadingGoogle: "Google ஏற்றுகிறது…",
    tapJoinGroup: "Join group அழுத்தவும்",
    closeJoinInstructions: "வழிமுறைகளை மூடவும்",
    theApp: "செயலி",
    fieldVisit: "கள வருகை",
    fieldPragathi: "பிரகதி",
    noPassword: "இந்த தளம் ஒருபோதும் கடவுச்சொல் கேட்காது.",
    feedback: "பின்னூட்டம்",
    feedbackType: "பின்னூட்ட வகை",
    messageLabel: "செய்தி",
    screenshotOptional: "திரைப்பிடிப்பு (விருப்பம்)",
    sendFeedbackBtn: "பின்னூட்டம் அனுப்பவும்",
    sending: "அனுப்புகிறது…",
    invalidEmailUi: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    messageTooShort: "குறைந்தது 10 எழுத்துகள் கொண்ட சிறு விளக்கத்தைச் சேர்க்கவும்.",
    tryAgain: "சிறிது நேரம் கழித்து மீண்டும் முயலவும்.",
    language: "மொழி",
    accountWarning: "Google கணக்கு எச்சரிக்கை",
    onboardingSteps: "சேரும் படிகள்",
    feedbackTypeBug: "பிழை",
    feedbackTypeSuggestion: "பரிந்துரை",
    feedbackTypeUsability: "பயன்பாடு",
    feedbackTypeAccessibility: "அணுகல்",
    feedbackTypeOther: "மற்றவை",
    joinBetaTitle: "AAC சிங்கள பீட்டாவில் சேரவும்",
    joinBetaSubtitle: "உங்கள் Android தொலைபேசியில் பயன்படுத்தும் Google கணக்கைப் பயன்படுத்துங்கள்.",
    googleVerified: "Google கணக்கு உறுதிசெய்யப்பட்டது",
    googleSignInFailed: "Google உள்நுழைவு முடியவில்லை. மீண்டும் முயலவும்.",
    googleSignInUnavailable: "Google உள்நுழைவு இன்னும் அமைக்கப்படவில்லை.",
    useDifferentAccount: "வேறு Google கணக்கைப் பயன்படுத்தவும்",
    signOut: "வெளியேறவும்",
    playStoreEmailLabel: "உங்கள் Google Play கணக்கு",
    playAccountImportant: "அதே Google கணக்கைப் பயன்படுத்துங்கள்",
    sameAccountGroupsAndPlay:
      "சோதனையாளர் குழுவிற்கும் Google Play-க்கும் அதே Google கணக்கைப் பயன்படுத்துங்கள்.",
    useThisSameAccountForGroup: "சோதனையாளர் குழுவில் சேரும்போது இந்த Google கணக்கையே பயன்படுத்துங்கள்.",
    switchIfAnotherAccount:
      "Google Groups-இல் வேறு கணக்கு இயங்கினால், Join group அழுத்துவதற்கு முன் மேலே காட்டிய கணக்கிற்கு மாறவும்.",
    afterJoinCheck: "சேர்ந்த பின் இங்கே திரும்பி Check My Access அழுத்தவும்.",
    groupsNewTabHint: "Google Groups புதிய தாவலில் திறக்கும். இந்தப் பக்கம் திறந்தே இருக்கும்.",
    lookForJoinGroup: "Join group பொத்தானைத் தேடுங்கள்",
    inTheGroup: "நீங்கள் சோதனையாளர் குழுவில் இருக்கிறீர்கள்",
    playUsingSame: "Google Play அதே கணக்கைப் பயன்படுத்துகிறதா எனப் பாருங்கள்.",
    feedbackPrompt: "பிழையோ பரிந்துரையோ உள்ளதா?",
    sendFeedback: "பின்னூட்டம் அனுப்பவும்",
    wrongAccountHeading: "தவறான Google கணக்கா?",
    wrongAccountHelp:
      "Google Groups-க்குத் திரும்பி, மேலே காட்டிய Google கணக்கிற்கு மாறி, சோதனையாளர் குழுவில் மீண்டும் சேரவும்.",
    checkAccessNotMember: "இந்த Google கணக்கு சோதனையாளர் குழுவில் இன்னும் காணப்படவில்லை.",
    checkAccessUnavailable: "உறுப்பினர் சரிபார்ப்பு தற்போது கிடைக்கவில்லை.",
    feedbackThanks: "நன்றி. உங்கள் பின்னூட்டம் தனிப்பட்ட முறையில் சேமிக்கப்பட்டது.",
    searchGroupHint:
      "Google Groups இந்தக் கணக்கில் உள்நுழையவில்லை என்றால், எங்கள் சோதனையாளர் குழுவைத் தேடிச் சேரவும்.",
    copyGroupName: "குழுப் பெயரை நகலெடுக்கவும்",
    groupNameCopied: "நகலெடுக்கப்பட்டது",
    registerWithEmail: "மின்னஞ்சலில் பதிவு செய்யவும்",
    orRegisterEmail: "அல்லது உங்கள் Play Store மின்னஞ்சலில் பதிவு செய்யவும்",
    emailRegistered: "இந்த மின்னஞ்சலில் பதிவு செய்யப்பட்டது",
    getOnGooglePlay: "Google Play-இல் பெறவும்",
    caseStudy: "ஆய்வு",
    gallery: "தொகுப்பு",
    downloadTheQr: "QR பதிவிறக்கவும்",
    qrLead: "AAC சிங்கள சோதனையாளர் தளத்தைத் திறக்க ஸ்கேன் செய்யவும்.",
    printQrPasses: "A4 QR பாஸ்களை அச்சிடவும்",
    printQrPassesLead: "ஒரு A4 தாள், இரண்டு லாமினேட் பாஸ்கள். நடுவில் வெட்டவும்.",
    contact: "தொடர்பு",
    contactName: "Yasas Pasindu Fernando",
    contactLocation: "ஹிக்கடுவை, இலங்கை",
    fieldExposure: "கள வெளிப்பாடு",
    chatTitle: "AAC கேளுங்கள்",
    chatLead: "சேர்தல், Play Store, பின்னூட்டம் மற்றும் Smart AAC ஆய்வுக்கான உதவியாளர்.",
    chatWelcome:
      "வணக்கம் — சோதனையாளர் குழு, Play நிறுவல், பின்னூட்டம் அல்லது ஆய்வில் உதவ முடியும். Google உள்நுழைவு குழு உறுப்பினர் ஆகாது.",
    chatPlaceholder: "சேர்தல், Play Store, செயலி பற்றி கேளுங்கள்…",
    chatSend: "அனுப்பு",
    chatClose: "அரட்டையை மூடு",
    chatTapToAsk: "கேட்க தட்டவும்",
    chatDismissTip: "குறிப்பை மூடு",
    invalidEmail: "சரியான Google கணக்கு மின்னஞ்சலை உள்ளிடவும்.",
    rateLimited: "அதிக கோரிக்கைகள். சில நிமிடங்கள் காத்திருந்து மீண்டும் முயலவும்.",
    almostReady: "நீங்கள் கிட்டத்தட்ட தயாராக இருக்கிறீர்கள்!",
    sameAccount: "நீங்கள் பதிவு செய்த அதே Google கணக்கைப் பயன்படுத்துங்கள்.",
    deviceAccount: "உங்கள் Android சாதனத்தில் அதே Play Store கணக்கைப் பயன்படுத்துங்கள்.",
    playStoreEveryone: "அனைவரும் Google Play-இல் பயன்படுத்தும் Google கணக்கையே பயன்படுத்த வேண்டும்.",
    playStoreEmailHint: "இது உங்கள் Android சாதனத்தில் பயன்படும் Google கணக்கு.",
    googleMissingEmail: "Google இந்தக் கணக்கிற்கு மின்னஞ்சலைப் பகிரவில்லை.",
    signInRequired: "தொடர Google மூலம் தொடரவும்.",
    joinGroupHint: "குழுவைத் திறந்து Join group அழுத்தவும். உங்கள் Play Store கணக்கைப் பயன்படுத்துங்கள்.",
    joinGroupModalTitle: "AAC சிங்கள சோதனையாளர்களில் சேரவும்",
    joinGroupModalLead: "AAC சிங்கள பீட்டாவில் சேர இன்னும் ஒரு படி உள்ளது.",
    playAccountShort: "Google Play-இல் பயன்படுத்தும் அதே Google கணக்கைப் பயன்படுத்துங்கள்.",
    usePlayStoreAccount: "குழுவில் சேர உங்கள் Play Store கணக்கைப் பயன்படுத்துங்கள்.",
    usePlayStoreAccountHeading: "உங்கள் Play Store கணக்கைப் பயன்படுத்துங்கள்",
    sameAccountPlayAndGroup: "சோதனையாளர் குழுவிற்கும் Google Play சோதனைக்கும் இந்தக் கணக்கையே பயன்படுத்துங்கள்.",
    accountEnteredLabel: "உங்கள் Google Play கணக்கு",
    authenticatedAccountIs: "நீங்கள் உறுதிப்படுத்திய கணக்கு:",
    whenJoiningExactAccount:
      "சோதனையாளர் குழுவில் சேரும்போது, Google Groups இந்தக் கணக்கிலேயே உள்நுழைந்திருப்பதை உறுதிப்படுத்துங்கள்.",
    groupsSignedInWarning: "Google Groups இந்தக் கணக்கிலேயே உள்நுழைந்திருப்பதை உறுதிப்படுத்துங்கள்.",
    beforeJoiningSignedIn: "சேருவதற்கு முன், Google Groups உள்நுழைந்திருப்பது:",
    alreadyJoined: "ஏற்கனவே சேர்ந்துவிட்டீர்களா?",
    nextPlayTest: "Google Play சோதனையில் சேரவும்",
    joinPlayTestHint: "இப்போது அதே Google கணக்கில் Google Play சோதனைப் பக்கத்தைத் திறக்கவும்.",
    installTitle: "AAC-Sinhala-ஐ நிறுவவும்",
    installHint: "சோதனையில் சேர்ந்த பின், உங்கள் Android தொலைபேசியில் Google Play-இலிருந்து AAC-Sinhala-ஐ நிறுவவும்.",
    startTestingTitle: "சோதனையைத் தொடங்கவும்",
    startTestingHint: "AAC-Sinhala-ஐத் திறந்து தொடர்பு அம்சங்களை முயலவும்.",
    checkAccessNotDetected: "இந்த Google கணக்கு சோதனையாளர் குழுவில் இன்னும் காணப்படவில்லை.",
    checkAccessRetry: "மேலே காட்டிய Google கணக்கில் குழுவில் சேர்ந்ததை உறுதிப்படுத்தி மீண்டும் முயலவும்.",
    verificationUnavailable: "உறுப்பினர் சரிபார்ப்பு கிடைக்கவில்லை",
    ready: "நீங்கள் தயாராக இருக்கிறீர்கள்!",
    readyToTest: "நீங்கள் AAC சிங்கள சோதனைக்கு தயாராக இருக்கிறீர்கள்",
    siteTitle: "AAC சிங்களம் — மூடிய சோதனை",
    siteDescription: "AAC சிங்கள மூடிய பீட்டாவில் சேரவும். குரல் தேவைப்படும் குழந்தைகளுக்கான தொடர்பு ஆதரவு.",
    continueWithGoogleAria: "Google மூலம் தொடரவும்",
    qrAlt: "https://aac.yasaboy.com/ க்கான QR குறியீடு",
    guideJoinAlt: "Join group பொத்தானை மஞ்சள் அம்பு காட்டும் Google Groups பக்கம்",
    fieldCentre: "மையம்",
    fieldContext: "சூழல்",
    appScreensAria: "iPhone சட்டங்களில் AAC சிங்கள செயலித் திரைகள்",
    appHomeTitle: "முகப்பு",
    appHomeBody: "ஒரு வகையைத் தேர்ந்தெடுத்து, செய்தியை உருவாக்கி, உரக்கப் பேசவும்.",
    appHomeAlt: "செய்தி உருவாக்கி மற்றும் வகைகள் கொண்ட AAC சிங்கள முகப்புத் திரை",
    appCardsTitle: "பட அட்டைகள்",
    appCardsBody: "புத்தகங்கள், உணவு, விளையாட்டு மற்றும் பிறவற்றுக்கான பெரிய, எளிதில் அழுத்தக்கூடிய அட்டைகள்.",
    appCardsAlt: "அன்றாடச் சொற்களுக்கான AAC சிங்கள பட அட்டைகள்",
    appEmotionTitle: "உணர்ச்சி கேமரா",
    appEmotionBody: "துணை வெளிப்பாட்டுக் குறிப்புகளுக்கான அமைதியான கேமரா காட்சி.",
    appEmotionAlt: "AAC சிங்கள உணர்ச்சி கேமரா திரை",
    appSettingsTitle: "அமைப்புகள்",
    appSettingsBody: "வீடு மற்றும் பள்ளிக்கான மொழி மற்றும் வகைத் தேர்வுகள்.",
    appSettingsAlt: "AAC சிங்கள அமைப்புகள் மற்றும் வகை விருப்பங்கள்",
    closeScreenshot: "திரைப்பிடிப்பை மூடு",
    enlargeScreenshot: "திரைப்பிடிப்பை பெரிதாக்கு",
    tapToEnlarge: "பெரிதாக்க படத்தைத் தட்டவும்",
    adminTitle: "சோதனையாளர் நிர்வாகம்",
    adminLead:
      "Cloudflare Access மூலம் பாதுகாக்கப்படுகிறது. மின்னஞ்சல்கள் இந்தப் பக்கத்திலேயே இருக்கும். Google உள்நுழைவும் தட்டச்சு மின்னஞ்சலும் சோதனையாளர் வரிகளை உருவாக்கும். இணைப்பு கிளிக்குகள் பதிவு நிகழ்வுகள் மட்டுமே, Google உறுப்பினர் அல்லது Play பதிவிறக்கச் சான்று அல்ல.",
    adminExportCsv: "CSV ஏற்றுமதி",
    adminProtected: "நிர்வாக அணுகல் Cloudflare Access மூலம் பாதுகாக்கப்படுகிறது.",
    adminTotalRequests: "மொத்த சோதனையாளர் கோரிக்கைகள்",
    adminGoogleSignups: "Google பதிவுகள்",
    adminEmailSignups: "மின்னஞ்சல் பதிவுகள்",
    adminFeedbackCount: "பின்னூட்ட எண்ணிக்கை",
    adminPendingGroup: "நிலுவை குழு சேர்வுகள்",
    adminPendingPlay: "நிலுவை Play சேர்வுகள்",
    adminCompletedFlows: "முடிந்த சேரும் ஓட்டங்கள்",
    adminNeedsAttention: "கவனம் தேவை",
    adminVerifiedMemberships: "உறுதிப்படுத்தப்பட்ட Google Group உறுப்பினர்கள்:",
    adminVerifiedHint: "இது 0 என்றால், நுகர்வோர் குழுவிற்கு உறுப்பினர் சரிபார்ப்பு கிடைக்கவில்லை.",
    adminRegistrants: "பதிவாளர்கள்",
    adminTesterRequests: "சோதனையாளர் கோரிக்கைகள்",
    adminColEmail: "மின்னஞ்சல்",
    adminColSignup: "பதிவு",
    adminColStatus: "நிலை",
    adminColRequested: "கோரப்பட்டது",
    adminColLastActivity: "கடைசி செயல்பாடு",
    adminColGroup: "குழு",
    adminColMembership: "உறுப்பினர்",
    adminOpened: "திறக்கப்பட்டது",
    adminVerified: "உறுதி",
    adminNotVerified: "உறுதி செய்யப்படவில்லை",
    adminSignupGoogle: "Google",
    adminSignupEmail: "மின்னஞ்சல்",
    adminNoFeedback: "இன்னும் பின்னூட்டம் இல்லை.",
    adminScreenshotAttached: "திரைப்பிடிப்பு இணைக்கப்பட்டது",
  },
} as const;

export type UiCopy = { [K in keyof (typeof UI_COPY)["en"]]: string };

export function isLocale(value: string | null | undefined): value is Locale {
  return value === "en" || value === "si" || value === "ta";
}

export function localizeApiMessage(message: string, t: UiCopy): string {
  for (const key of Object.keys(USER_MESSAGES) as (keyof typeof USER_MESSAGES)[]) {
    if (USER_MESSAGES[key] === message) return t[key];
  }
  return message;
}
