import { USER_MESSAGES } from "./types";

export type Locale = "en" | "si" | "ta";

export const LOCALES: readonly Locale[] = ["en", "si", "ta"] as const;

export const LOCALE_LABELS: Record<Locale, string> = {
  en: "EN",
  si: "සිං",
  ta: "த",
};

const extraEn = {
  skipToContent: "Skip to content",
  join: "Join",
  continueWithGoogle: "Continue with Google",
  joinTesterGroup: "Join the tester group",
  joinPlayAndInstall: "Join Play test and install",
  stepJoinGroup: "Join group",
  stepCheckAccess: "Check access",
  stepInstallApp: "Install app",
  step1Title: "1. Join the tester group",
  step2Title: "2. Check access",
  step3Title: "3. Join Play test, then install",
  openTesterGroup: "Open Tester Group",
  openTesterGroupAgain: "Open Tester Group again",
  openTesterGroupAria: "Open Tester Group (opens in a new tab)",
  checkMyAccess: "Check My Access",
  checking: "Checking…",
  joinGooglePlayTest: "Join Google Play Test",
  joinPlayAria: "Join Google Play Test (opens in a new tab)",
  installApp: "Install AAC-Sinhala",
  installAria: "Install AAC-Sinhala (opens in a new tab)",
  loading: "Loading…",
  loadingGoogle: "Loading Google…",
  tapJoinGroup: "Tap Join group",
  closeJoinInstructions: "Close join instructions",
  theApp: "The app",
  fieldVisit: "Field visit",
  fieldPragathi: "Pragathi",
  noPassword: "This site never asks for a password.",
  feedback: "Feedback",
  feedbackType: "Feedback type",
  messageLabel: "Message",
  screenshotOptional: "Screenshot (optional)",
  sendFeedbackBtn: "Send feedback",
  sending: "Sending…",
  invalidEmailUi: "Please enter a valid email address.",
  messageTooShort: "Please include a short description (at least 10 characters).",
  tryAgain: "Please try again in a moment.",
  language: "Language",
  accountWarning: "Google account warning",
  onboardingSteps: "Onboarding steps",
  feedbackTypeBug: "Bug",
  feedbackTypeSuggestion: "Suggestion",
  feedbackTypeUsability: "Usability",
  feedbackTypeAccessibility: "Accessibility",
  feedbackTypeOther: "Other",
} as const;

export const UI_COPY = {
  en: {
    ...USER_MESSAGES,
    ...extraEn,
  },
  si: {
    ...USER_MESSAGES,
    ...extraEn,
    skipToContent: "අන්තර්ගතයට යන්න",
    join: "එක්වන්න",
    continueWithGoogle: "Google සමඟ ඉදිරියට යන්න",
    joinTesterGroup: "පරීක්ෂක කණ්ඩායමට එක්වන්න",
    joinPlayAndInstall: "Play පරීක්ෂණයට එක්වී ස්ථාපනය කරන්න",
    stepJoinGroup: "කණ්ඩායමට එක්වන්න",
    stepCheckAccess: "ප්‍රවේශය බලන්න",
    stepInstallApp: "යෙදුම ස්ථාපනය",
    step1Title: "1. පරීක්ෂක කණ්ඩායමට එක්වන්න",
    step2Title: "2. ප්‍රවේශය බලන්න",
    step3Title: "3. Play පරීක්ෂණයට එක්වී ස්ථාපනය කරන්න",
    openTesterGroup: "පරීක්ෂක කණ්ඩායම විවෘත කරන්න",
    openTesterGroupAgain: "පරීක්ෂක කණ්ඩායම නැවත විවෘත කරන්න",
    openTesterGroupAria: "පරීක්ෂක කණ්ඩායම විවෘත කරන්න (නව ටැබයක)",
    checkMyAccess: "මගේ ප්‍රවේශය පරීක්ෂා කරන්න",
    checking: "පරීක්ෂා කරමින්…",
    joinGooglePlayTest: "Google Play පරීක්ෂණයට එක්වන්න",
    joinPlayAria: "Google Play පරීක්ෂණයට එක්වන්න (නව ටැබයක)",
    installApp: "AAC-Sinhala ස්ථාපනය කරන්න",
    installAria: "AAC-Sinhala ස්ථාපනය කරන්න (නව ටැබයක)",
    loading: "පූරණය වෙමින්…",
    loadingGoogle: "Google පූරණය වෙමින්…",
    tapJoinGroup: "Join group ඔබන්න",
    closeJoinInstructions: "උපදෙස් වසන්න",
    theApp: "යෙදුම",
    fieldVisit: "ක්ෂේත්‍ර සංචාරය",
    fieldPragathi: "ප්‍රගති",
    noPassword: "මෙම අඩවිය කිසිදා මුරපදයක් ඉල්ලන්නේ නැත.",
    feedback: "ප්‍රතිපෝෂණය",
    feedbackType: "ප්‍රතිපෝෂණ වර්ගය",
    messageLabel: "පණිවිඩය",
    screenshotOptional: "තිර රුව (අත්‍යවශ්‍ය නැත)",
    sendFeedbackBtn: "ප්‍රතිපෝෂණය යවන්න",
    sending: "යවමින්…",
    invalidEmailUi: "වලංගු ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.",
    messageTooShort: "අඩුම තරමේ අකුරු 10ක කෙටි විස්තරයක් ඇතුළත් කරන්න.",
    tryAgain: "මඳ වේලාවකින් නැවත උත්සාහ කරන්න.",
    language: "භාෂාව",
    accountWarning: "Google ගිණුම් අනතුරු ඇඟවීම",
    onboardingSteps: "එක්වීමේ පියවර",
    feedbackTypeBug: "දෝෂයක්",
    feedbackTypeSuggestion: "යෝජනාවක්",
    feedbackTypeUsability: "භාවිතය",
    feedbackTypeAccessibility: "ප්‍රවේශ්‍යතාව",
    feedbackTypeOther: "වෙනත්",
    joinBetaTitle: "AAC සිංහල බීටාවට එක්වන්න",
    joinBetaSubtitle: "ඔබේ Android දුරකථනයේ භාවිතා කරන Google ගිණුම භාවිතා කරන්න.",
    googleVerified: "Google ගිණුම තහවුරු විය",
    googleSignInFailed: "Google පිවිසුම සම්පූර්ණ නොවීය. නැවත උත්සාහ කරන්න.",
    googleSignInUnavailable: "Google පිවිසුම තවම සකසා නැත.",
    useDifferentAccount: "වෙනත් Google ගිණුමක් භාවිතා කරන්න",
    signOut: "ඉවත් වන්න",
    playStoreEmailLabel: "ඔබේ Google Play ගිණුම",
    playAccountImportant: "එකම Google ගිණුම භාවිතා කරන්න",
    sameAccountGroupsAndPlay: "පරීක්ෂක කණ්ඩායමට සහ Google Play සඳහා එකම Google ගිණුම භාවිතා කරන්න.",
    useThisSameAccountForGroup: "පරීක්ෂක කණ්ඩායමට එක්වන විට මෙම Google ගිණුමම භාවිතා කරන්න.",
    switchIfAnotherAccount:
      "Google Groups හි වෙනත් ගිණුමක් සක්‍රිය නම්, Join group ඔබන්නට පෙර ඉහත පෙන්වන ගිණුමට මාරු වන්න.",
    afterJoinCheck: "එක්වීමෙන් පසු මෙහි ආපසු එන්න, Check My Access ඔබන්න.",
    groupsNewTabHint: "Google Groups නව ටැබයක විවෘත වේ. මෙම පිටුව විවෘතව තිබේ.",
    lookForJoinGroup: "Join group බොත්තම සොයන්න",
    inTheGroup: "ඔබ පරීක්ෂක කණ්ඩායමේ සිටී",
    playUsingSame: "Google Play එකම ගිණුම භාවිතා කරනවාදැයි බලන්න.",
    feedbackPrompt: "දෝෂයක් හෝ යෝජනාවක් තිබේද?",
    sendFeedback: "ප්‍රතිපෝෂණය යවන්න",
    wrongAccountHeading: "වැරදි Google ගිණුමක්ද?",
    wrongAccountHelp:
      "Google Groups වෙත ආපසු ගොස්, ඉහත පෙන්වන Google ගිණුමට මාරු වී, පරීක්ෂක කණ්ඩායමට නැවත එක්වන්න.",
    checkAccessNotMember: "මෙම Google ගිණුම පරීක්ෂක කණ්ඩායමේ තවම හමු නොවීය.",
    checkAccessUnavailable: "සාමාජිකත්වය තහවුරු කිරීම දැන් ලබාගත නොහැක.",
    feedbackThanks: "ස්තුතියි. ඔබේ ප්‍රතිපෝෂණය පෞද්ගලිකව සුරකින ලදී.",
    searchGroupHint:
      "Google Groups මෙම ගිණුමෙන් පිවිසී නැත්නම්, අපේ පරීක්ෂක කණ්ඩායම සොයා එක්වන්න.",
    copyGroupName: "කණ්ඩායම් නම පිටපත් කරන්න",
    groupNameCopied: "පිටපත් විය",
  },
  ta: {
    ...USER_MESSAGES,
    ...extraEn,
    skipToContent: "உள்ளடக்கத்திற்குச் செல்லவும்",
    join: "சேரவும்",
    continueWithGoogle: "Google மூலம் தொடரவும்",
    joinTesterGroup: "சோதனையாளர் குழுவில் சேரவும்",
    joinPlayAndInstall: "Play சோதனையில் சேர்ந்து நிறுவவும்",
    stepJoinGroup: "குழுவில் சேரவும்",
    stepCheckAccess: "அணுகலைச் சரிபார்க்கவும்",
    stepInstallApp: "செயலியை நிறுவவும்",
    step1Title: "1. சோதனையாளர் குழுவில் சேரவும்",
    step2Title: "2. அணுகலைச் சரிபார்க்கவும்",
    step3Title: "3. Play சோதனையில் சேர்ந்து நிறுவவும்",
    openTesterGroup: "சோதனையாளர் குழுவைத் திறக்கவும்",
    openTesterGroupAgain: "சோதனையாளர் குழுவை மீண்டும் திறக்கவும்",
    openTesterGroupAria: "சோதனையாளர் குழுவைத் திறக்கவும் (புதிய தாவல்)",
    checkMyAccess: "என் அணுகலைச் சரிபார்க்கவும்",
    checking: "சரிபார்க்கிறது…",
    joinGooglePlayTest: "Google Play சோதனையில் சேரவும்",
    joinPlayAria: "Google Play சோதனையில் சேரவும் (புதிய தாவல்)",
    installApp: "AAC-Sinhala-ஐ நிறுவவும்",
    installAria: "AAC-Sinhala-ஐ நிறுவவும் (புதிய தாவல்)",
    loading: "ஏற்றுகிறது…",
    loadingGoogle: "Google ஏற்றுகிறது…",
    tapJoinGroup: "Join group அழுத்தவும்",
    closeJoinInstructions: "வழிமுறைகளை மூடவும்",
    theApp: "செயலி",
    fieldVisit: "கள வருகை",
    fieldPragathi: "பிரகதி",
    noPassword: "இந்த தளம் ஒருபோதும் கடவுச்சொல் கேட்காது.",
    feedback: "பின்னூட்டம்",
    feedbackType: "பின்னூட்ட வகை",
    messageLabel: "செய்தி",
    screenshotOptional: "திரைப்பிடிப்பு (விருப்பம்)",
    sendFeedbackBtn: "பின்னூட்டம் அனுப்பவும்",
    sending: "அனுப்புகிறது…",
    invalidEmailUi: "சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    messageTooShort: "குறைந்தது 10 எழுத்துகள் கொண்ட சிறு விளக்கத்தைச் சேர்க்கவும்.",
    tryAgain: "சிறிது நேரம் கழித்து மீண்டும் முயலவும்.",
    language: "மொழி",
    accountWarning: "Google கணக்கு எச்சரிக்கை",
    onboardingSteps: "சேரும் படிகள்",
    feedbackTypeBug: "பிழை",
    feedbackTypeSuggestion: "பரிந்துரை",
    feedbackTypeUsability: "பயன்பாடு",
    feedbackTypeAccessibility: "அணுகல்",
    feedbackTypeOther: "மற்றவை",
    joinBetaTitle: "AAC சிங்கள பீட்டாவில் சேரவும்",
    joinBetaSubtitle: "உங்கள் Android தொலைபேசியில் பயன்படுத்தும் Google கணக்கைப் பயன்படுத்துங்கள்.",
    googleVerified: "Google கணக்கு உறுதிசெய்யப்பட்டது",
    googleSignInFailed: "Google உள்நுழைவு முடியவில்லை. மீண்டும் முயலவும்.",
    googleSignInUnavailable: "Google உள்நுழைவு இன்னும் அமைக்கப்படவில்லை.",
    useDifferentAccount: "வேறு Google கணக்கைப் பயன்படுத்தவும்",
    signOut: "வெளியேறவும்",
    playStoreEmailLabel: "உங்கள் Google Play கணக்கு",
    playAccountImportant: "அதே Google கணக்கைப் பயன்படுத்துங்கள்",
    sameAccountGroupsAndPlay:
      "சோதனையாளர் குழுவிற்கும் Google Play-க்கும் அதே Google கணக்கைப் பயன்படுத்துங்கள்.",
    useThisSameAccountForGroup: "சோதனையாளர் குழுவில் சேரும்போது இந்த Google கணக்கையே பயன்படுத்துங்கள்.",
    switchIfAnotherAccount:
      "Google Groups-இல் வேறு கணக்கு இயங்கினால், Join group அழுத்துவதற்கு முன் மேலே காட்டிய கணக்கிற்கு மாறவும்.",
    afterJoinCheck: "சேர்ந்த பின் இங்கே திரும்பி Check My Access அழுத்தவும்.",
    groupsNewTabHint: "Google Groups புதிய தாவலில் திறக்கும். இந்தப் பக்கம் திறந்தே இருக்கும்.",
    lookForJoinGroup: "Join group பொத்தானைத் தேடுங்கள்",
    inTheGroup: "நீங்கள் சோதனையாளர் குழுவில் இருக்கிறீர்கள்",
    playUsingSame: "Google Play அதே கணக்கைப் பயன்படுத்துகிறதா எனப் பாருங்கள்.",
    feedbackPrompt: "பிழையோ பரிந்துரையோ உள்ளதா?",
    sendFeedback: "பின்னூட்டம் அனுப்பவும்",
    wrongAccountHeading: "தவறான Google கணக்கா?",
    wrongAccountHelp:
      "Google Groups-க்குத் திரும்பி, மேலே காட்டிய Google கணக்கிற்கு மாறி, சோதனையாளர் குழுவில் மீண்டும் சேரவும்.",
    checkAccessNotMember: "இந்த Google கணக்கு சோதனையாளர் குழுவில் இன்னும் காணப்படவில்லை.",
    checkAccessUnavailable: "உறுப்பினர் சரிபார்ப்பு தற்போது கிடைக்கவில்லை.",
    feedbackThanks: "நன்றி. உங்கள் பின்னூட்டம் தனிப்பட்ட முறையில் சேமிக்கப்பட்டது.",
    searchGroupHint:
      "Google Groups இந்தக் கணக்கில் உள்நுழையவில்லை என்றால், எங்கள் சோதனையாளர் குழுவைத் தேடிச் சேரவும்.",
    copyGroupName: "குழுப் பெயரை நகலெடுக்கவும்",
    groupNameCopied: "நகலெடுக்கப்பட்டது",
  },
} as const;

export type UiCopy = { [K in keyof (typeof UI_COPY)["en"]]: string };

export function isLocale(value: string | null | undefined): value is Locale {
  return value === "en" || value === "si" || value === "ta";
}
